initial implementation
RebelCode/vc-paged pull request #1
Opened 2017-12-28 14:30 UTC by romalytvynenko

Initial implementation of paged component

2017-12-28 15:13 UTC, XedinUnknown commented
It's true that we cannot assume any particular purpose of this component; only that it has 0 or more pages, and that it knows about them. However, I don't really understand right now what purpose this component serves, especially since the bulk of its functionality seems to be in the root template.

Also, I thought that this component would somehow extend the `Repeater` component. Each page has something in common, and something different. Then, the Paged component repeats these pages, rendering them and their content. Extensions can add on top of that to make tabs, or a slider. The visible/active pages are controlled by the limited collection. That's what I had in mind.

2018-01-05 15:23 UTC, XedinUnknown requested changes
- Documentation and tags missing, including for tests.
- Not sure how template gets data of the current subject.
- Tests don't seem to be usable outside of the browser, and use a global.

2018-01-05 15:23 UTC, XedinUnknown commented on src/index.js
> +                    return (pageTemplate, page = null) => {
The `page` argument seems to be unused. What is the role of this argument?

2018-01-05 15:23 UTC, XedinUnknown commented on src/index.js
> +            isPageActive (item) {
Missing `since` tag.

2018-01-05 15:23 UTC, XedinUnknown commented on src/index.js
> +            wrapper: {
Missing `since` tag.

2018-01-05 15:23 UTC, XedinUnknown commented on src/index.js
> +            selectedKeys: {
Missing `since` tag.

2018-01-05 15:23 UTC, XedinUnknown commented on src/index.js
> +            items: {
Missing `since` tag.

2018-01-05 15:23 UTC, XedinUnknown commented on src/index.js
> +export function CfPaged (Vue) {
Missing `since` tag.

2018-01-05 15:23 UTC, XedinUnknown commented on src/index.js
> +            pageWrapper: {
Missing `since` tag.

2018-01-05 15:23 UTC, XedinUnknown commented on src/index.js
> +            isPageActive (item) {
Missing `since` tag.

2018-01-05 15:23 UTC, XedinUnknown commented on src/index.js
> +        render (h) {
Missing docs.

2018-01-05 15:23 UTC, XedinUnknown commented on src/index.js
> +                    template: this.pageWrapper(page.render(ctx), page)
How does the data of the page itself get passed to the template?

2018-01-05 15:23 UTC, XedinUnknown commented on tests/e2e/app.js
> +document.addEventListener('DOMContentLoaded', () => {
Looks like this test cannot be run in a non-browser environment. How can it be changed to work with a simulated DOM?

2018-01-05 17:06 UTC, romalytvynenko commented
Pushed that changes. 

About running that test in non-browser environment. Should we run Vue component's e2e test on non-browser environment? This is strange for me, because while looking for framework I saw that:
1. All JS e2e frameworks work inside browser environments. 
2. e2e testing point is to test something in it's environment, so Vue component's e2e test should be run in browser. Or I've missed something?

2018-01-05 17:39 UTC, XedinUnknown commented
The browser, document, window etc are not the concern of template rendering. Rendering is related to the DOM. If you can have the DOM, but not everything else, this would be the perfect test.

2018-01-08 08:09 UTC, romalytvynenko commented
@XedinUnknown, I've removed `document` dependency

2018-02-08 13:54 UTC, XedinUnknown approved these changes

2018-02-08 13:54 UTC, merged